// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChsHbZMQ_sJ5V89UdjozpI4AdqQ60487I',
    appId: '1:844225663348:web:3d880afc62011bf7c59c21',
    messagingSenderId: '844225663348',
    projectId: 'dr-bread',
    authDomain: 'dr-bread.firebaseapp.com',
    storageBucket: 'dr-bread.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr55J4_cBwZ2X0VL6PxNRAwIj_W8nJga4',
    appId: '1:844225663348:android:b316cde92a843808c59c21',
    messagingSenderId: '844225663348',
    projectId: 'dr-bread',
    storageBucket: 'dr-bread.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp8XsOYDCcfBjE7Pluf9G4XR2QnHgakfQ',
    appId: '1:844225663348:ios:6c28aee4a47d097dc59c21',
    messagingSenderId: '844225663348',
    projectId: 'dr-bread',
    storageBucket: 'dr-bread.firebasestorage.app',
    iosBundleId: 'com.dhkim.drbread.drBreadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp8XsOYDCcfBjE7Pluf9G4XR2QnHgakfQ',
    appId: '1:844225663348:ios:6c28aee4a47d097dc59c21',
    messagingSenderId: '844225663348',
    projectId: 'dr-bread',
    storageBucket: 'dr-bread.firebasestorage.app',
    iosBundleId: 'com.dhkim.drbread.drBreadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChsHbZMQ_sJ5V89UdjozpI4AdqQ60487I',
    appId: '1:844225663348:web:e3875052447517dbc59c21',
    messagingSenderId: '844225663348',
    projectId: 'dr-bread',
    authDomain: 'dr-bread.firebaseapp.com',
    storageBucket: 'dr-bread.firebasestorage.app',
  );
}
